// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt6qhvHSTbiC5ndcNcbhZNsX1Al7jVRMc',
    appId: '1:74929280614:web:d82c80a7de4c7741803fa7',
    messagingSenderId: '74929280614',
    projectId: 'wocproject-aaa9d',
    authDomain: 'wocproject-aaa9d.firebaseapp.com',
    storageBucket: 'wocproject-aaa9d.appspot.com',
    measurementId: 'G-VM04KDVFR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbUGMx2hwSeI5Jt1XI7BokFhq6ayygFj8',
    appId: '1:74929280614:android:d782a7421a598dd3803fa7',
    messagingSenderId: '74929280614',
    projectId: 'wocproject-aaa9d',
    storageBucket: 'wocproject-aaa9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAu-0zaBM2A6RjLUWXo6kCIJgxolhXHek',
    appId: '1:74929280614:ios:8fddfcbe92447521803fa7',
    messagingSenderId: '74929280614',
    projectId: 'wocproject-aaa9d',
    storageBucket: 'wocproject-aaa9d.appspot.com',
    iosBundleId: 'com.example.wocproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAu-0zaBM2A6RjLUWXo6kCIJgxolhXHek',
    appId: '1:74929280614:ios:c85d15c218d7a214803fa7',
    messagingSenderId: '74929280614',
    projectId: 'wocproject-aaa9d',
    storageBucket: 'wocproject-aaa9d.appspot.com',
    iosBundleId: 'com.example.wocproject.RunnerTests',
  );
}
